'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const { loadSandbox } = require('./helpers/sandbox');

function loadPdfUtils() {
  return loadSandbox({ scripts: ['pdflite.js', 'utils.js'] });
}

/** Two synthetic orders: one long enough to paginate, one small. No real data. */
function syntheticOrders() {
  const bigItems = [];
  for (let i = 1; i <= 45; i++) {
    bigItems.push({
      productName: `Test Item ${i} (Family Size) 24oz \\ Special`,
      quantity: String((i % 3) + 1),
      price: `$${i}.99`,
      deliveryStatus: i % 2 ? 'Delivered' : 'Canceled',
    });
  }
  return [
    {
      orderNumber: '2000001-1111111',
      orderDate: 'Jan 5, 2026',
      items: bigItems,
      subtotalBeforeSavings: '$120.00',
      savings: '$10.00',
      orderSubtotal: '$110.00',
      deliveryCharges: '',
      bagFee: '',
      tax: '$7.15',
      tip: '$5.00',
      refund: '',
      donations: '',
      orderTotal: '$122.15',
      address: '123 Test Lane, Springfield, ZZ 00000',
      paymentSplit: 'VISA ending in 0000: $122.15',
      sellers: 'Walmart.com',
      trackingNumbers: '1Z999TEST0000000000',
      deliveredDate: 'Jan 7, 2026',
      paymentMethodDetails: [
        { brand: 'VISA', ending: 'ending in 0000', amount: '$122.15' },
      ],
    },
    {
      orderNumber: '2000002-2222222',
      orderDate: 'Feb 1, 2026',
      items: [
        { productName: 'Bananas (bunch)', quantity: '1', price: '$1.28', deliveryStatus: 'Delivered' },
      ],
      subtotalBeforeSavings: '',
      savings: '',
      orderSubtotal: '$1.28',
      deliveryCharges: '$3.99',
      bagFee: '',
      tax: '$0.09',
      tip: '',
      refund: '',
      donations: '',
      orderTotal: '$5.36',
      address: '',
      paymentSplit: '',
      sellers: '',
      trackingNumbers: '',
      deliveredDate: '',
    },
  ];
}

/** Assert bytes look like a Uint8Array (cross-realm safe) and decode them. */
function pdfToString(bytes) {
  assert.equal(Object.prototype.toString.call(bytes), '[object Uint8Array]',
    'builder should return a Uint8Array');
  return Buffer.from(bytes).toString('latin1');
}

/** Read the page count from the /Pages tree. */
function pageCount(str) {
  const match = str.match(/\/Type \/Pages \/Kids \[[^\]]*\] \/Count (\d+)/);
  assert.ok(match, 'pages tree with /Count should exist');
  return Number(match[1]);
}

/** Verify every xref offset lands exactly on its "N 0 obj" header. */
function assertValidXref(str) {
  const xrefIdx = str.lastIndexOf('\nxref\n');
  assert.ok(xrefIdx > 0, 'xref section should exist');
  const xrefOffset = xrefIdx + 1;

  const startxrefMatch = str.match(/startxref\n(\d+)\n%%EOF/);
  assert.ok(startxrefMatch, 'startxref should be present');
  assert.equal(Number(startxrefMatch[1]), xrefOffset,
    'startxref should point at the xref section');

  const lines = str.slice(xrefOffset).split('\n');
  assert.equal(lines[0], 'xref');
  const [start, count] = lines[1].split(' ').map(Number);
  assert.equal(start, 0, 'xref subsection should start at object 0');
  assert.match(lines[2], /^0000000000 65535 f\s*$/, 'object 0 should be free');
  for (let n = 1; n < count; n++) {
    const entry = lines[2 + n];
    const m = entry.match(/^(\d{10}) (\d{5}) n\s*$/);
    assert.ok(m, `xref entry for object ${n} should be in-use: "${entry}"`);
    const offset = parseInt(m[1], 10);
    const header = `${n} 0 obj`;
    assert.equal(str.slice(offset, offset + header.length), header,
      `xref offset ${offset} for object ${n} should point at "${header}"`);
  }
}

test('buildReceiptPdf renders a paginated multi-order PDF receipt', () => {
  const sandbox = loadPdfUtils();
  const str = pdfToString(sandbox.buildReceiptPdf(syntheticOrders()));

  assert.ok(str.startsWith('%PDF-1.4'), 'file should start with %PDF-1.4');
  assert.match(str.trimEnd(), /%%EOF$/, 'file should end with %%EOF');

  // Order 1 (45 items) needs 2+ pages; order 2 starts on its own page.
  assert.ok(pageCount(str) >= 3, `expected >= 3 pages, got ${pageCount(str)}`);

  assert.ok(str.includes('Walmart Order #2000001-1111111'), 'order 1 header text');
  assert.ok(str.includes('Walmart Order #2000002-2222222'), 'order 2 header text');
  assert.ok(str.includes('Order total'), 'totals block should render');
  // Parentheses and backslashes in item names must be PDF-escaped.
  assert.ok(str.includes('Bananas \\(bunch\\)'), 'parens should be escaped');
  assert.ok(str.includes('24oz \\\\ Special'), 'backslashes should be escaped');
  // Footer note is stamped on every page.
  const footers = str.split('Generated by Walmart Invoice Exporter').length - 1;
  assert.equal(footers, pageCount(str), 'each page should carry the footer note');
});

test('buildReceiptPdf output has a valid xref table', () => {
  const sandbox = loadPdfUtils();
  const str = pdfToString(sandbox.buildReceiptPdf(syntheticOrders()));
  assertValidXref(str);
});

test('buildReceiptPdf skips empty totals and meta lines', () => {
  const sandbox = loadPdfUtils();
  const [, smallOrder] = syntheticOrders();
  const str = pdfToString(sandbox.buildReceiptPdf(smallOrder));

  assert.equal(pageCount(str), 1, 'small single order should fit one page');
  assert.ok(str.includes('Delivery charges'), 'non-empty totals row renders');
  assert.ok(!str.includes('Bag fee'), 'empty totals rows are skipped');
  assert.ok(!str.includes('Ship to:'), 'empty meta lines are skipped');
});

test('buildSummaryPdf renders the Quick Export summary table', () => {
  const sandbox = loadPdfUtils();
  const rows = [
    { orderNumber: '2000003-3333333', orderDate: 'Mar 2, 2026', itemCount: 4, orderTotal: '$44.10' },
    { orderNumber: '2000004-4444444', orderDate: 'Mar 9, 2026', itemCount: '', orderTotal: '' },
  ];
  const str = pdfToString(sandbox.buildSummaryPdf(rows));

  assert.ok(str.startsWith('%PDF-1.4'), 'file should start with %PDF-1.4');
  assert.match(str.trimEnd(), /%%EOF$/, 'file should end with %%EOF');
  assert.ok(str.includes('Walmart Orders Summary'), 'title should render');
  assert.ok(str.includes('2000003-3333333'), 'row order number should render');
  assert.ok(str.includes('$44.10'), 'row total should render');
  assertValidXref(str);
});
